"""
Interactive configuration manager for API keys and model providers.
"""
import os
from pathlib import Path
from typing import Optional, Dict
from rich.console import Console
from rich.prompt import Prompt, Confirm
from rich.table import Table
from agentic_doc.config import Config, load_config, save_config

console = Console()


class ConfigManager:
    """Manage configuration and API keys."""
    
    def __init__(self):
        self.config = load_config()
        self.env_file = Path(".env")
    
    def interactive_setup(self):
        """Interactive configuration wizard."""
        console.print("\n[bold blue]🔧 Agentic Doc Configuration Wizard[/bold blue]\n")
        
        # Select provider
        console.print("[bold]Select Model Provider:[/bold]")
        console.print("1. Gemini (Google) - FREE")
        console.print("2. OpenAI - PAID")
        console.print("3. Mock (Testing)")
        
        choice = Prompt.ask("Choose provider", choices=["1", "2", "3"], default="1")
        
        provider_map = {"1": "gemini", "2": "openai", "3": "mock"}
        provider = provider_map[choice]
        
        self.config.model_provider = provider
        
        # Configure API keys
        if provider == "gemini":
            self._setup_gemini()
        elif provider == "openai":
            self._setup_openai()
        else:
            console.print("[yellow]Mock provider selected - no API key needed[/yellow]")
        
        # Save configuration
        save_config(self.config)
        console.print(f"\n[green]✓ Configuration saved to .agentic-doc.yml[/green]")
        
        # Show summary
        self.show_config()
    
    def _setup_gemini(self):
        """Setup Gemini API key."""
        console.print("\n[bold cyan]Gemini Configuration[/bold cyan]")
        console.print("Get your FREE API key at: https://makersuite.google.com/app/apikey")
        
        current_key = os.getenv("GEMINI_API_KEY", "")
        if current_key:
            console.print(f"[dim]Current key: {current_key[:10]}...[/dim]")
            if not Confirm.ask("Update API key?", default=False):
                return
        
        api_key = Prompt.ask("Enter Gemini API Key", password=True)
        
        if api_key:
            self._save_env_var("GEMINI_API_KEY", api_key)
            console.print("[green]✓ Gemini API key saved[/green]")
        
        # Model selection
        model = Prompt.ask(
            "Gemini model",
            default=self.config.gemini_model,
            choices=["gemini-2.0-flash-exp", "gemini-1.5-flash", "gemini-1.5-pro"]
        )
        self.config.gemini_model = model
    
    def _setup_openai(self):
        """Setup OpenAI API key."""
        console.print("\n[bold cyan]OpenAI Configuration[/bold cyan]")
        console.print("Get your API key at: https://platform.openai.com/api-keys")
        
        current_key = os.getenv("OPENAI_API_KEY", "")
        if current_key:
            console.print(f"[dim]Current key: {current_key[:10]}...[/dim]")
            if not Confirm.ask("Update API key?", default=False):
                return
        
        api_key = Prompt.ask("Enter OpenAI API Key", password=True)
        
        if api_key:
            self._save_env_var("OPENAI_API_KEY", api_key)
            console.print("[green]✓ OpenAI API key saved[/green]")
        
        # Model selection
        model = Prompt.ask(
            "OpenAI model",
            default=self.config.openai_model,
            choices=["gpt-4o", "gpt-4o-mini", "gpt-4-turbo", "gpt-3.5-turbo"]
        )
        self.config.openai_model = model
    
    def _save_env_var(self, key: str, value: str):
        """Save environment variable to .env file."""
        env_vars = {}
        
        # Read existing .env
        if self.env_file.exists():
            with open(self.env_file, 'r') as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith('#') and '=' in line:
                        k, v = line.split('=', 1)
                        env_vars[k.strip()] = v.strip()
        
        # Update key
        env_vars[key] = value
        
        # Write back
        with open(self.env_file, 'w') as f:
            f.write("# Agentic Doc API Keys\n")
            f.write("# Generated by configuration wizard\n\n")
            for k, v in env_vars.items():
                f.write(f"{k}={v}\n")
        
        # Load into current environment
        os.environ[key] = value
    
    def switch_provider(self, provider: str):
        """Switch to a different provider."""
        valid_providers = ["openai", "gemini", "mock"]
        
        if provider not in valid_providers:
            console.print(f"[red]Invalid provider: {provider}[/red]")
            console.print(f"Valid options: {', '.join(valid_providers)}")
            return
        
        self.config.model_provider = provider
        save_config(self.config)
        
        console.print(f"[green]✓ Switched to {provider}[/green]")
        
        # Check if API key is configured
        if provider == "gemini" and not os.getenv("GEMINI_API_KEY"):
            console.print("[yellow]⚠ Warning: GEMINI_API_KEY not set[/yellow]")
            console.print("Run 'agentic-doc configure' to set up your API key")
        elif provider == "openai" and not os.getenv("OPENAI_API_KEY"):
            console.print("[yellow]⚠ Warning: OPENAI_API_KEY not set[/yellow]")
            console.print("Run 'agentic-doc configure' to set up your API key")
    
    def show_config(self):
        """Display current configuration."""
        console.print("\n[bold]Current Configuration:[/bold]\n")
        
        table = Table(show_header=True, header_style="bold cyan")
        table.add_column("Setting", style="dim")
        table.add_column("Value")
        
        table.add_row("Provider", self.config.model_provider)
        table.add_row("Root Path", self.config.root_path)
        
        if self.config.model_provider == "openai":
            table.add_row("OpenAI Model", self.config.openai_model)
            key = os.getenv("OPENAI_API_KEY", "")
            status = f"{'✓ Set' if key else '✗ Not set'}"
            table.add_row("OpenAI API Key", status)
        elif self.config.model_provider == "gemini":
            table.add_row("Gemini Model", self.config.gemini_model)
            key = os.getenv("GEMINI_API_KEY", "")
            status = f"{'✓ Set' if key else '✗ Not set'}"
            table.add_row("Gemini API Key", status)
        
        console.print(table)
        console.print()
    
    def validate_config(self) -> bool:
        """Validate current configuration."""
        provider = self.config.model_provider
        
        if provider == "mock":
            return True
        
        if provider == "openai":
            if not os.getenv("OPENAI_API_KEY"):
                console.print("[red]✗ OpenAI API key not configured[/red]")
                console.print("Run: agentic-doc configure")
                return False
        
        if provider == "gemini":
            if not os.getenv("GEMINI_API_KEY"):
                console.print("[red]✗ Gemini API key not configured[/red]")
                console.print("Run: agentic-doc configure")
                return False
        
        return True
